
robot:
  path: assets/usd/pumbaa/*.usd
  position: [0, -3, 1.3]
  orient: [1, 0, 0, 0]
  scale: [1, 1, 1]

obstacle:
  path: assets/usd/obstacle/model-stairs.usd
  position: [5.2, 0, 0]
  orient: [0, 0, 90]
  scale: [1, 11, 1]

  up_groud:
    path: assets/usd/obstacle/ground.usd
    position: [ 0, -2.5, 1 ]
    scale: [ 1, 0.5, 1 ]

  ground:
    path: assets/usd/obstacle/ground.usd

map:

  lower: [-11, -11, -0.1]
  upper: [11, 11, 2]
  cell_size: 0.05




