
robot:
  path: assets/usd/pumbaa/*.usd
  position: [0, 0, 0.35]
  orient: [0, 0, 0, 1]
  scale: [1, 1, 1]

obstacle:
  ground:
    path: assets/usd/obstacle/ground.usd

map:
  lower: [-11, -11, -0.1]
  upper: [11, 11, 2]
  cell_size: 0.05

task_info:
  start_point: [2.00, 0, 0.1]
  start_orient: [0, 0, 3.14]
  target_point: [-2.00, 0, 0.1]



