name: benchmark_plum_blossom_pile
robot:
  path: assets/usd/pumbaa/*.usd
  position: [2, 0, 0.2]
  orient: [0, 0, 0, 1]
  scale: [1, 1, 1]

obstacle:
  o1:
    path: assets/usd/obstacle/plum_plane.usd
    position: [0, -1.2, 0]
    orient: [1, 0, 0, 0]
    scale: [1, 1, 1]
  o3:
    path: assets/usd/obstacle/plum_plane.usd
    position: [ 0, 1.2, 0 ]
    orient: [ 1, 0, 0, 0 ]
    scale: [ 1, 1, 1 ]
  o2:
    path: assets/usd/obstacle/plum_plane.usd
    position: [ 0, 0, 0 ]
    orient: [ 1, 0, 0, 0 ]
    scale: [ 1, 1, 1 ]

  ground:
    path: assets/usd/obstacle/ground.usd

map:
  path: assets/map/model-benchmark_plum_blossom_pile.map
  lower: [-10, -10, 0]
  upper: [10, 10, 2]
  cell_size: 0.05




