
robot:
  path: assets/usd/pumbaa/*.usd
  position: [3, 0, 0.2]
  orient: [0, 0, 0, 1]
  scale: [1, 1, 1]

obstacle:
  path: assets/usd/obstacle/model-stairs.usd
  position: [0, -5.2, 0]
  scale: [1, 11, 1]

  up_groud:
    path: assets/usd/obstacle/ground.usd
    position: [ -2.5, 0, 1 ]
    scale: [ 0.5, 1, 1 ]

  ground:
    path: assets/usd/obstacle/ground.usd

map:
  lower: [-11, -11, -0.1]
  upper: [11, 11, 2]
  cell_size: 0.05
