name: benchmark_flatland
robot:
  path: assets/usd/pumbaa/*.usd
  position: [0, 0, 0.2]
  orient: [0, 0, 0, 1]
  scale: [1, 1, 1]

obstacle:

  ground:
    path: assets/usd/obstacle/ground.usd

map:
  path: assets/map/benchmark_flatland.map
  lower: [-11, -11, -0.1]
  upper: [11, 11, 2]
  cell_size: 0.05




