
robot:
  path: assets/usd/pumbaa/*.usd
  position: [0, 0, 3.1]
  orient: [0, 0, 0, 1]
  scale: [1, 1, 1]


terrain:
  t1:
    position: [19, 19, 0.5]
    orient: [ 0, 0, 0, 1 ]
    base_config:
      terrain_width: 38
      terrain_length: 38
      horizontal_scale: 0.05
      vertical_scale: 0.005
      slope_threshold: 100
    terrain_list:
      - type_name: curriculum_steps_down
        min_h: 0.2
        max_h: 0.6
        env_width: 3
        env_length: 3
        num_terrains: 7
        num_levels: 7
        border_size: 1.8
        seed: 40

map:

  lower: [-21, -21, -1]
  upper: [21, 21, 2]
  cell_size: 0.05

camera:
  position: [2, 30, 15]
  target: [0, 0, -5]


