
robot:
  path: assets/usd/pumbaa/*.usd
  position: [0, 0, 3.5]
  orient: [0, 0, 0, 1]
  scale: [1, 1, 1]


terrain:
  t1:
    position: [10, 10, 0.9]
    orient: [ 0, 0, 0, 1 ]
    base_config:
      terrain_width: 20
      terrain_length: 20
      horizontal_scale: 0.01
      vertical_scale: 0.005
      slope_threshold: ~
      mesh: assets/mesh/curriculum_stairs_down.stl
    terrain_list:
      - type_name: curriculum_stairs_down
        min_step_width: 0.2
        max_step_width: 0.3
        min_angle: 20
        max_angle: 45

        env_width: 2.5
        env_length: 2.5
        num_terrains: 4
        num_levels: 4
        border_size: 1.8
        seed: 40

map:
  lower: [-12, -12, -1]
  upper: [12, 12, 3]
  cell_size: 0.05

camera:
  position: [0, 18, 16]
  target: [0, -2, -6]


