
robot:
  path: assets/usd/pumbaa/*.usd
  position: [2, 0, 0.13]
  orient: [0, 0, 0, 1]
  scale: [1, 1, 1]

obstacle:
  path: assets/usd/obstacle/cube.usd
  position: [ -2, -1.5, 0 ]
  scale: [ 3, 3, 0.4 ]

  ground:
    path: assets/usd/obstacle/ground.usd

map:
  lower: [-11, -11, -0.1]
  upper: [11, 11, 2]
  cell_size: 0.05

camera:
  position: [0, 5, 1.75]
  target: [0, -2.5, 0]

task_info:
  start_point: [2, 0, 0.13]
  start_orient: [0, 0, 3.14]
  target_point: [0, 0, 0.53]
