
robot:
  path: assets/usd/pumbaa/*.usd
  position: [3, 0, 0.2]
  orient: [0, 0, 0, 1]
  scale: [1, 1, 1]

obstacle:
  path: assets/usd/obstacle/terrain_stairs_2.usd
  position: [1.7, 1.2, 0]
  orient: [0, 0, 0, 1]
  scale: [1, 2, 1]

  ground:
    path: assets/usd/obstacle/ground.usd

map:
  lower: [-11, -11, -0.1]
  upper: [11, 11, 2]
  cell_size: 0.05

task_info:
  start_point: [3.08, 0, 0.1]
  start_orient: [0, 0, 3.14]
  target_point: [-1.02, 0, 1.14]
