
robot:
  path: assets/usd/pumbaa/*.usd
  position: [2, 0, 0.1]
  orient: [0, 0, 0, 1]
  scale: [1, 1, 1]

obstacle:
  left:
    path: assets/usd/obstacle/cube.usd
    position: [ -1, 0.8725, 0 ]
    scale: [ 2, 0.15, 0.3 ]
  right:
    path: assets/usd/obstacle/cube.usd
    position: [ -1, -1, 0 ]
    scale: [ 2, 0.15, 0.3 ]
  center:
    path: assets/usd/obstacle/cube.usd
    position: [ 0.925, -1, 0 ]
    orient: [0.92388, 0, 0, 0.38268]
    scale: [ 0.15, 2.7, 0.3 ]
  ground:
    path: assets/usd/obstacle/ground.usd

map:
  lower: [-11, -11, -0.1]
  upper: [11, 11, 2]
  cell_size: 0.05

task_info:
  start_point: [2, 0, 0.42]
  start_orient: [0, 0, 3.14]
  target_point: [-2, 0, 0.11]