
robot:
  path: assets/usd/pumbaa/*.usd
  position: [-0.0, 0, 1.14]
  orient: [0, 0, 0, 1]
  scale: [1, 1, 1]

obstacle:
  path: assets/usd/obstacle/terrain_stairs_2.usd
  position: [1.6, 1.5, 0]
  orient: [0, 0, 0, 1]
  scale: [1, 2.5, 1]

  cube:
    path: assets/usd/obstacle/cube.usd
    position: [ -1, -1.5, 0 ]
    scale: [ 3.5, 3, 1 ]

  ground:
    path: assets/usd/obstacle/ground.usd

map:
  lower: [-11, -11, -0.1]
  upper: [11, 11, 2]
  cell_size: 0.05

camera:
  position: [0, 7, 2]
  target: [0, 0, 0]

task_info:
  start_point: [-0.0, 0, 1.14]
  start_orient: [0, 0, 3.14]
  target_point: [-3.0, 0, 1.14]
