
robot:
  path: assets/usd/pumbaa/*.usd
  position: [2, 0, 0.1]
  orient: [0, 0, 0, 1]
  scale: [1, 1, 1]

obstacle:
  path: assets/usd/obstacle/cube.usd
  position: [ -0.75, -1, 0 ]
  scale: [ 1.5, 1, 0.3 ]

  ground:
    path: assets/usd/obstacle/ground.usd

map:
  lower: [-11, -11, -0.1]
  upper: [11, 11, 2]
  cell_size: 0.05

task_info:
  start_point: [1.75, 0, 0.11]
  start_orient: [0, 0, 3.14]
  target_point: [-1.75, 0, 0.11]