
robot:
  path: assets/usd/pumbaa/*.usd
  position: [3, 0, 0.2]
  orient: [0, 0, 0, 1]
  scale: [1, 1, 1]

obstacle:
  path: assets/usd/obstacle/terrain_stepfield.usd
  position: [0.48144, -0.01079, -0.1]
  orient: [0.38268, 0, 0, 0.92388]
  scale: [1, 1, 1]

  ground:
    path: assets/usd/obstacle/ground.usd

map:
  lower: [-11, -11, -0.1]
  upper: [11, 11, 2]
  cell_size: 0.05

task_info:
  start_point: [2.57, 0, 0.11]
  start_orient: [0, 0, 3.14]
  target_point: [-1.6, 0, 0.11]
