
robot:
  path: assets/usd/pumbaa/*.usd
  position: [2, 0, 0.1]
  orient: [0, 0, 0, 1]
  scale: [1, 1, 1]

obstacle:
  path: assets/usd/obstacle/cube.usd
  position: [ -1, -1.5, 0 ]
  scale: [ 2, 3, 0.4 ]

  ground:
    path: assets/usd/obstacle/ground.usd

map:
  lower: [-11, -11, -0.1]
  upper: [11, 11, 2]
  cell_size: 0.05
