
robot:
  path: assets/usd/pumbaa/*.usd
  position: [0, 0, 1.7]
  orient: [0, 0, 0, 1]
  scale: [1, 1, 1]

obstacle:
  path: assets/usd/obstacle/stair_and_slip.usd
  position: [0, 0, 0.0]
  orient: [1, 0, 0, 0]
  scale: [1, 1, 1]


terrain:
  t1:
    position: [12, 16, 0.0]
    orient: [ 0, 0, 0, 1 ]
    base_config:
      terrain_width: 24
      terrain_length: 32
      horizontal_scale: 0.05
      vertical_scale: 0.005
      slope_threshold: 0.5
    terrain_list:
      - type_name: train_mixed

map:
  lower: [-14, -18, -1]
  upper: [14, 18, 2]
  cell_size: 0.05

camera:
  position: [0, 30, 15]
  target: [0, 0, -5]


