
robot:
  path: assets/usd/pumbaa/*.usd
  position: [0, 0, 0.2]
  orient: [0, 0, 0, 1]
  scale: [1, 1, 1]


terrain:
  t1:
    position: [1.25, 1.5, 0]
    orient: [ 0, 0, 0, 1 ]
    base_config:
      terrain_width: 2.5
      terrain_length: 3
      horizontal_scale: 0.05
      vertical_scale: 0.005
      slope_threshold: 1
    terrain_list:
      - type_name: flat
      - type_name: flat
        height: 0.2
      - type_name: flat
        height: 0.25
      - type_name: flat
        height: 0.35
      - type_name: flat
        height: 0.4

map:
  lower: [-14, -4, -1]
  upper: [4, 4, 3]
  cell_size: 0.05

camera:
  position: [-5, 8, 8]
  target: [-5, 0, 0]

