
robot:
  path: assets/usd/pumbaa/*.usd
  position: [0, 0, 2.7]
  orient: [0, 0, 0, 1]
  scale: [1, 1, 1]

terrain:
  t1:
    position: [1.25, 1.5, 0]
    orient: [ 0, 0, 0, 1 ]
    base_config:
      terrain_width: 3.0
      terrain_length: 3
      horizontal_scale: 0.05
      vertical_scale: 0.005
      slope_threshold: 0.1
    terrain_list:
      - type_name: flat
        height: 2.5
      - type_name: stairs
        step_width: 0.3
        step_height: -0.2
      - type_name: flat
      - type_name: stairs
        step_width: 0.2
        step_height: 0.2
      - type_name: flat

map:
  lower: [-16, -4, -2]
  upper: [4, 4, 5]
  cell_size: 0.05

camera:
  position: [-6, 8, 12]
  target: [-6, -1, 2]

