
prim_config:
  set_attrs:
    - prim_path: terrain
      attr_name: "xformOp:translate"
      value: [21, 21, 0.5]
    - prim_path: terrain
      attr_name: "xformOp:orient"
      value: [ 0, 0, 0, 1.0 ]

map:
  lower: [-24, -24, -1]
  upper: [24, 24, 3]
  cell_size: 0.05

camera:
  position: [0, 40, 25]
  target: [0, 0, -5]

