
prim_config:
  set_attrs:
    - prim_path: terrain
      attr_name: "xformOp:translate"
      value: [15, 15, 0.5]
    - prim_path: terrain
      attr_name: "xformOp:orient"
      value: [ 0, 0, 0, 1.0 ]

map:
  lower: [-17, -17, -1]
  upper: [17, 17, 2]
  cell_size: 0.05

camera:
  position: [0, 25, 15]
  target: [0, -2, -5]


