prim_config:
  set_attrs:
    - prim_path: terrain
      attr_name: "xformOp:translate"
      value: [25, 25, 0.5]
    - prim_path: terrain
      attr_name: "xformOp:orient"
      value: [ 0, 0, 0, 1.0 ]

map:

  lower: [-27, -27, -1]
  upper: [27, 27, 3]
  cell_size: 0.05

camera:
  position: [0, 40, 25]
  target: [0, 0, -5]

