
prim_config:
  set_attrs:
    - prim_path: terrain
      attr_name: "xformOp:translate"
      value: [19, 19, 0.5]
    - prim_path: terrain
      attr_name: "xformOp:orient"
      value: [ 0, 0, 0, 1.0 ]

map:
  lower: [-21, -21, -1]
  upper: [21, 21, 2]
  cell_size: 0.05

camera:
  position: [2, 30, 15]
  target: [0, 0, -5]


