
prim_config:
  set_attrs:
    - prim_path: terrain
      attr_name: "xformOp:translate"
      value: [0, 0, 0.35]
    - prim_path: terrain
      attr_name: "xformOp:orient"
      value: [ 1.0, 0, 0, 0.0 ]

map:
  lower: [-11, -11, -0.1]
  upper: [11, 11, 2]
  cell_size: 0.05

camera:
  position: [0, 40, 25]
  target: [0, 0, -5]

